spring:
  datasource:
    url: jdbc:h2:~/data/matzip
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test